# These are supported funding model platforms
# Available funding options of the project. You can specify up to four [sponsored GitHub accounts](https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors),
# up to four custom URLs, and one account per supported external funding platform.

github: xkeshav
