title: "[General] "
labels: ["General Introduction"]
body:
  - type: markdown
    attributes:
      value: |
        introduce yourself!

  - type: textarea
    id: improvements
    attributes:
      label: Top 3 improvements
      description: "What are the top 3 improvements we could make to this project?"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true

  - type: textarea
    id: has-id
    attributes:
      label: write us suggestion
      description: A description about suggestions to help you
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: By submitting this announcement, you agree to follow our [Contributing Guidelines](https://github.com/xkeshav/color-collector/blob/main/.github/CONTRIBUTING.md).
      options:
        - label: I've made research efforts and searched the documentation
          required: true
