/* eslint-disable @typescript-eslint/naming-convention */

export const extensionID = 'xkeshav.css-color-collector';

export const DOCUMENT_MINIMUM_LENGTH = 12; // *{color:var(--defaultSelector__txt--1)} is the minimum color containing css content

export const rootComment = '/* following variables are generated by css color collector */';


export const PATTERN_LIST = {
	PROPERTY: '(?<PROPERTY>[\\w-]+[^:])(?=:\s*)',
	SELECTOR_WITH_MEDIA: '(^(?!.*@media)[\\t ]*(?<SELECTOR>[@a-zA-Z#.:*[][^{\\/]*\\s*){[\\s\\S]*?})',
	COLOR_HEX_FORMAT: '(?<HEX_COLOR>#[0-9a-f]{3,8})',
	COLOR_NON_HEX_FORMAT: '((?<NON_HEX_COLOR>(?:rgba?|hsla?|hwb|lab|oklab|lch|oklch)?\\((:?-?[\\d\.]+%?(deg|rad|grad|turn)?[,\\s]+){2,3}[\\s\/]*[\\d\.]+%?\\)))',
	COLOR_FUNCTION: '(?<COLOR_FUNCTION>(\\bcolor\\b)\\(.*\\))',
	WORD: '(\\w+)',
	IMPORT_STMT: '(?<=@)\\bimport\\b\\s*(?<IMPORT>.*)',
	COLOR_NAME: '(?<![.#-])\\s*(?<COLOR_NAME>\\b(?:var(--COLOR_NON_HEX_FORMAT__defaultElement--2)|var(--COLOR_NON_HEX_FORMAT__defaultElement--3)|var(--COLOR_NON_HEX_FORMAT__defaultElement--4)|var(--COLOR_NON_HEX_FORMAT__defaultElement--5)|var(--COLOR_NON_HEX_FORMAT__defaultElement--6)|var(--defaultSelector__txt--1)|var(--COLOR_NON_HEX_FORMAT__defaultElement--7)|var(--COLOR_NON_HEX_FORMAT__defaultElement--8)|var(--COLOR_NON_HEX_FORMAT__defaultElement--9)|var(--COLOR_NON_HEX_FORMAT__defaultElement--10)|var(--COLOR_NON_HEX_FORMAT__defaultElement--11)|var(--COLOR_NON_HEX_FORMAT__defaultElement--12)|var(--COLOR_NON_HEX_FORMAT__defaultElement--13)|var(--COLOR_NON_HEX_FORMAT__defaultElement--14)|var(--COLOR_NON_HEX_FORMAT__defaultElement--15)|var(--COLOR_NON_HEX_FORMAT__defaultElement--16)|var(--COLOR_NON_HEX_FORMAT__defaultElement--17)|var(--COLOR_NON_HEX_FORMAT__defaultElement--18)|var(--COLOR_NON_HEX_FORMAT__defaultElement--19)|var(--COLOR_NON_HEX_FORMAT__defaultElement--20)|var(--COLOR_NON_HEX_FORMAT__defaultElement--21)|var(--COLOR_NON_HEX_FORMAT__defaultElement--22)|var(--COLOR_NON_HEX_FORMAT__defaultElement--23)|var(--COLOR_NON_HEX_FORMAT__defaultElement--24)|var(--COLOR_NON_HEX_FORMAT__defaultElement--25)|var(--COLOR_NON_HEX_FORMAT__defaultElement--26)|var(--COLOR_NON_HEX_FORMAT__defaultElement--27)|var(--COLOR_NON_HEX_FORMAT__defaultElement--28)|var(--COLOR_NON_HEX_FORMAT__defaultElement--29)|var(--COLOR_NON_HEX_FORMAT__defaultElement--30)|var(--COLOR_NON_HEX_FORMAT__defaultElement--31)|var(--COLOR_NON_HEX_FORMAT__defaultElement--32)|var(--COLOR_NON_HEX_FORMAT__defaultElement--33)|var(--COLOR_NON_HEX_FORMAT__defaultElement--34)|var(--COLOR_NON_HEX_FORMAT__defaultElement--35)|var(--COLOR_NON_HEX_FORMAT__defaultElement--36)|var(--COLOR_NON_HEX_FORMAT__defaultElement--37)|var(--COLOR_NON_HEX_FORMAT__defaultElement--38)|var(--COLOR_NON_HEX_FORMAT__defaultElement--39)|var(--COLOR_NON_HEX_FORMAT__defaultElement--40)|var(--COLOR_NON_HEX_FORMAT__defaultElement--41)|var(--COLOR_NON_HEX_FORMAT__defaultElement--42)|var(--COLOR_NON_HEX_FORMAT__defaultElement--43)|var(--COLOR_NON_HEX_FORMAT__defaultElement--44)|var(--COLOR_NON_HEX_FORMAT__defaultElement--45)|var(--COLOR_NON_HEX_FORMAT__defaultElement--46)|var(--COLOR_NON_HEX_FORMAT__defaultElement--47)|var(--COLOR_NON_HEX_FORMAT__defaultElement--48)|var(--COLOR_NON_HEX_FORMAT__defaultElement--49)|var(--COLOR_NON_HEX_FORMAT__defaultElement--50)|var(--COLOR_NON_HEX_FORMAT__defaultElement--51)|var(--COLOR_NON_HEX_FORMAT__defaultElement--52)|var(--COLOR_NON_HEX_FORMAT__defaultElement--53)|var(--COLOR_NON_HEX_FORMAT__defaultElement--54)|var(--COLOR_NON_HEX_FORMAT__defaultElement--55)|var(--COLOR_NON_HEX_FORMAT__defaultElement--56)|var(--COLOR_NON_HEX_FORMAT__defaultElement--57)|var(--COLOR_NON_HEX_FORMAT__defaultElement--58)|var(--COLOR_NON_HEX_FORMAT__defaultElement--59)|var(--COLOR_NON_HEX_FORMAT__defaultElement--60)|var(--COLOR_NON_HEX_FORMAT__defaultElement--61)|var(--COLOR_NON_HEX_FORMAT__defaultElement--62)|var(--COLOR_NON_HEX_FORMAT__defaultElement--63)|var(--COLOR_NON_HEX_FORMAT__defaultElement--64)|var(--COLOR_NON_HEX_FORMAT__defaultElement--65)|var(--COLOR_NON_HEX_FORMAT__defaultElement--66)|var(--COLOR_NON_HEX_FORMAT__defaultElement--67)|var(--COLOR_NON_HEX_FORMAT__defaultElement--68)|var(--COLOR_NON_HEX_FORMAT__defaultElement--69)|var(--COLOR_NON_HEX_FORMAT__defaultElement--70)|var(--COLOR_NON_HEX_FORMAT__defaultElement--71)|var(--COLOR_NON_HEX_FORMAT__defaultElement--72)|var(--COLOR_NON_HEX_FORMAT__defaultElement--73)|var(--COLOR_NON_HEX_FORMAT__defaultElement--74)|var(--COLOR_NON_HEX_FORMAT__defaultElement--75)|var(--COLOR_NON_HEX_FORMAT__defaultElement--76)|var(--COLOR_NON_HEX_FORMAT__defaultElement--77)|var(--COLOR_NON_HEX_FORMAT__defaultElement--78)|var(--COLOR_NON_HEX_FORMAT__defaultElement--79)|var(--COLOR_NON_HEX_FORMAT__defaultElement--80)|var(--COLOR_NON_HEX_FORMAT__defaultElement--81)|var(--COLOR_NON_HEX_FORMAT__defaultElement--82)|var(--COLOR_NON_HEX_FORMAT__defaultElement--83)|var(--COLOR_NON_HEX_FORMAT__defaultElement--84)|var(--COLOR_NON_HEX_FORMAT__defaultElement--85)|var(--COLOR_NON_HEX_FORMAT__defaultElement--86)|var(--COLOR_NON_HEX_FORMAT__defaultElement--87)|var(--COLOR_NON_HEX_FORMAT__defaultElement--88)|var(--COLOR_NON_HEX_FORMAT__defaultElement--89)|var(--COLOR_NON_HEX_FORMAT__defaultElement--90)|var(--COLOR_NON_HEX_FORMAT__defaultElement--91)|var(--COLOR_NON_HEX_FORMAT__defaultElement--92)|var(--COLOR_NON_HEX_FORMAT__defaultElement--93)|var(--COLOR_NON_HEX_FORMAT__defaultElement--94)|var(--COLOR_NON_HEX_FORMAT__defaultElement--95)|var(--COLOR_NON_HEX_FORMAT__defaultElement--96)|var(--COLOR_NON_HEX_FORMAT__defaultElement--97)|var(--COLOR_NON_HEX_FORMAT__defaultElement--98)|var(--COLOR_NON_HEX_FORMAT__defaultElement--99)|var(--COLOR_NON_HEX_FORMAT__defaultElement--100)|var(--COLOR_NON_HEX_FORMAT__defaultElement--101)|var(--COLOR_NON_HEX_FORMAT__defaultElement--102)|var(--COLOR_NON_HEX_FORMAT__defaultElement--103)|var(--COLOR_NON_HEX_FORMAT__defaultElement--104)|var(--COLOR_NON_HEX_FORMAT__defaultElement--105)|var(--COLOR_NON_HEX_FORMAT__defaultElement--106)|var(--COLOR_NON_HEX_FORMAT__defaultElement--107)|var(--COLOR_NON_HEX_FORMAT__defaultElement--108)|var(--COLOR_NON_HEX_FORMAT__defaultElement--109)|var(--COLOR_NON_HEX_FORMAT__defaultElement--110)|var(--COLOR_NON_HEX_FORMAT__defaultElement--111)|var(--COLOR_NON_HEX_FORMAT__defaultElement--112)|var(--COLOR_NON_HEX_FORMAT__defaultElement--113)|var(--COLOR_NON_HEX_FORMAT__defaultElement--114)|var(--COLOR_NON_HEX_FORMAT__defaultElement--115)|var(--COLOR_NON_HEX_FORMAT__defaultElement--116)|var(--COLOR_NON_HEX_FORMAT__defaultElement--117)|var(--COLOR_NON_HEX_FORMAT__defaultElement--118)|var(--COLOR_NON_HEX_FORMAT__defaultElement--119)|var(--COLOR_NON_HEX_FORMAT__defaultElement--120)|var(--COLOR_NON_HEX_FORMAT__defaultElement--121)|var(--COLOR_NON_HEX_FORMAT__defaultElement--122)|var(--COLOR_NON_HEX_FORMAT__defaultElement--123)|var(--COLOR_NON_HEX_FORMAT__defaultElement--124)|var(--COLOR_NON_HEX_FORMAT__defaultElement--125)|var(--COLOR_NON_HEX_FORMAT__defaultElement--126)|var(--COLOR_NON_HEX_FORMAT__defaultElement--127)|var(--COLOR_NON_HEX_FORMAT__defaultElement--128)|var(--COLOR_NON_HEX_FORMAT__defaultElement--129)|var(--COLOR_NON_HEX_FORMAT__defaultElement--130)|var(--COLOR_NON_HEX_FORMAT__defaultElement--131)|var(--COLOR_NON_HEX_FORMAT__defaultElement--132)|var(--COLOR_NON_HEX_FORMAT__defaultElement--133)|var(--COLOR_NON_HEX_FORMAT__defaultElement--134)|var(--COLOR_NON_HEX_FORMAT__defaultElement--135)|var(--COLOR_NON_HEX_FORMAT__defaultElement--136)|var(--COLOR_NON_HEX_FORMAT__defaultElement--137)|var(--COLOR_NON_HEX_FORMAT__defaultElement--138)|var(--COLOR_NON_HEX_FORMAT__defaultElement--139)|var(--COLOR_NON_HEX_FORMAT__defaultElement--140)|var(--COLOR_NON_HEX_FORMAT__defaultElement--141)|var(--COLOR_NON_HEX_FORMAT__defaultElement--142)|var(--COLOR_NON_HEX_FORMAT__defaultElement--143)|var(--COLOR_NON_HEX_FORMAT__defaultElement--144)|var(--COLOR_NON_HEX_FORMAT__defaultElement--145)|var(--COLOR_NON_HEX_FORMAT__defaultElement--146))\\b)', /* 148 named color  */
	ROOT_SELECTOR: '(?<!\\/\\*.*)(?<=:)(?<ROOT_BLOCK>\\b(root)\\b\\s*(?={))'
};


export const COLOR_PROPERTY_LIST = {
	'background': 'bg',
	'background-color': 'bg',
	'background-image': 'bg__img',
	'border': 'border',
	'border-color': 'border',
	'border-bottom': 'border__bottom',
	'border-bottom-color': 'border__bottom',
	'border-left': 'border__left',
	'border-left-color': 'border__left',
	'border-right': 'border__right',
	'border-right-color': 'border__right',
	'border-top': 'border__top',
	'border-top-color': 'border__top',
	'border-block-color': 'border__block',
	'border-inline-color': 'border__inline',
	'border-block-start-color': 'border__block--start',
	'border-block-end-color': 'border__block--end',
	'border-inline-start-color': 'border__inline--start',
	'border-inline-end-color': 'border__inline--end',
	'box-shadow': 'box__shadow',
	'caret-color': 'caret',
	'color': 'txt',
	'column-rule': 'column__rule',
	'column-rule-color': 'column__rule',
	'filter': 'filter',
	'opacity': 'opacity',
	'outline': 'outline',
	'outline-color': 'outline',
	'scrollbar-color': 'scrollbar',
	'text-decoration': 'txt__decoration',
	'text-decoration-color': 'txt__decoration',
	'text-shadow': 'txt__shadow',
	'text-emphasis-color': 'txt__emphasis',
	'-webkit-text-stroke': 'txt__stroke',
	'-webkit-text-stroke-color': 'txt__stroke',
	'-webkit-text-fill-color': 'txt__fill'
};

export const PROPERTY_ALIAS_MAPPER = new Map(Object.entries(COLOR_PROPERTY_LIST));
